Travis CI: Disable SSH StrictHostKeyChecking with lftp
This is not necessary with "trusty" distribution,
but it is a requirement before switching to "xenial".
Otherwise deployment to SourceForge fails with:
Fatal error: Host key verification failed